### ISSUE TITLE
Question: ServeError type switch

### ISSUE THREAD

**Issue by fredbi** [go-openapi/errors#13]
I am wondering how we may produce a testcase to enter this type type switch branch here:
https://github.com/go-openapi/errors/blob/7bcb96a367bac6b76e6e42fa84155bb5581dcff8/api.go#L128

I assume the intent is to detect a nil pointer on a type implementing the Error interface{}, but it looks like things don't work that way...

In my opinion, really guarding against nil here would involve some reflection, with something like:
reflect.ValueOf(e).IsNil() when reflect.TypeOf(e) is a nillable type...

I did not feel like polluting the code with reflection so I gave up. But the question is still itching...
Similar type switches do exist in the validate package, which I consistently failed to explore with valid test cases...

Please advise.

**Comment by casualjim** [comment]
it will be nil if the value that was put in there was nil in the first place. It's not nil with a concrete type.

https://play.golang.org/p/s0jy8cApvQ-

**Comment by fredbi** [comment]
Thank you for the example.
However, the problem I got is not to produce a nil error, but to get into the type switch guard.

Your example asserts nil on the variable. But when performing the type switch, the switch does not recognize it as the tested interface (i.e. `case error:`):

```go
package main

import (
	"log"
	"reflect"
)

func main() {
	e1 := useMyErr()
	//e2 := useMyErr2()
	log.Println("useMyErr null:", e1 == nil)
	log.Println("useMyErr2 null:", useMyErr2() == nil)
	log.Println("useMyErr3 null:", useMyErr3() == nil)

	switch err := useMyErr2().(type) {
	case error:
		if err == nil {
			// how do you get there!
			log.Printf("Err is nil")
		} else {
			log.Printf("Err is not nil")
		}
	default:
		log.Printf("Type: %#v", err)
		log.Printf("TypeOf: %v", reflect.TypeOf(err))
		log.Printf("ValueOf: %v", reflect.ValueOf(err))
	}
}

type myErr struct {
	msg string
}

func (m *myErr) Error() string { return m.msg }

func useMyErr() error {
	var e *myErr
	return e
}
func useMyErr2() error {
	return nil
}
func useMyErr3() error {
	var e error
	return e
}
```

To me it seems that:
1. We may have a pointer receiver verifying the interface, but it is not himself nil: their _value_ may be nul.
Hence the proposal to reflect further on, a bit like one may find [here](https://github.com/go-openapi/validate/blob/9286f6d0e5c1ffc7cf2bda1d59291dc3c4f2f828/type.go#L91).
2. The switch may resolve to a "case nil" type (I added this in `api.go`)

I found a similar testability problem, wondering about dead code in validate, here: https://github.com/go-openapi/validate/blob/9286f6d0e5c1ffc7cf2bda1d59291dc3c4f2f828/values.go#L42 (the comment in code is mine).
